### ISSUE TITLE
#1 Startup settings

### ISSUE THREAD

**Issue by Annibezh** [future-stardust/url-shrtnr-le-gushqua#13]
Нам, як команді, потрібно налаштувати проект для старту роботи над ним та успішним закінченням.
**Критерії:**
1. Створити базові класи та інтерфейси для основних частин програми (авторизація, зберігання даних, посилання на лінки)
2. Налаштувати зв'язок мід ними, DI

**Comment by quppeq** [comment]
По суті це 2 задачі.
Зараз в нас це гілка db_dump і authorization
і як не дивно - вони разом йдуть в нас.
